[package]
name = "redjubjub-zebra"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
rand_core = "0.5"
thiserror = "1.0"
blake2b_simd = "0.5"
jubjub = "0.3"

[dev-dependencies]
rand = "0.7"

[features]
nightly = []
